### ISSUE TITLE
-d option

### ISSUE THREAD

**Issue by mlerogers** [gtfold/gtfold#15]
-d option for maximum contact distance is almost behaving like a minimum contact distance

eg:
using a big contact distance (> length of sequence) should behave like there is no -d flag (default) but when I tried it on a trna sequence (length 76, -d 100) it returned no structure.

conversely, when I did -2 or 0 it returned the default structure

**Comment by mlerogers** [comment]
Oh, and if you don't input a number with -d, GTfold seg faults. It assumes -d is 0 if I have options after it, but not if I run GTfold with -d as the last option (with no number)

**Comment by zetches** [comment]
Change this inside the withinCD method of constraints.cc: 

return (j-i>=contactDistance) 

to 

return(j-i<=contactDistance) 

That should fix it - sorry, apparently wasn't thinking right when I wrote it... 

The segfaulting is probably an error in the argument parser in main.cc.

**Comment by shelswenson** [comment]
add checks to make sure the argument given was a positive integer:
check that the argument given is the same as string(atoi(arg)), and check that the argument given is greater than zero.

**Comment by pgaurav** [comment]
this is fixed
