### ISSUE TITLE
high energy for structure with no bp

### ISSUE THREAD

**Issue by mlerogers** [gtfold/gtfold#17]
Don't know if we want to stick with convention and assign a structure with no bp a free energy of 0 kcal/n, but when I run GTfold with -d such that no structure is possible, it returns a ridiculously high free energy (around 10,000 kcal for a 76 base sequence)

**Comment by shelswenson** [comment]
Hardcode to be zero.

**Comment by pgaurav** [comment]
fixed, please close this
