### ISSUE TITLE
-o options needs work

### ISSUE THREAD

**Issue by mlerogers** [gtfold/gtfold#21]
Using the -o option with nothing specified after it results in a seg fault.

Also, if you input a file name with a '/' like 'temp/mfe.ct' or '///' no file is created, although GTfold acts like it did. Probably we should scold the user for improper name rather than carrying on.

**Comment by shelswenson** [comment]
when we first read in the file, we should make sure we can write to that file. If we can't we should print a warning and either die or _say_ we're _not_ gonna make that file, and tell the user where we put it instead.
